version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: node -v
      - run: uname -a
      - run: echo "Hello, Arm!"

workflows:
  start-jobs:
    jobs:
      - build-medium
