version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: node -v
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh &>/dev/null
      - run: PUPPETEER_PRODUCT=chrome $HOME/.deno/bin/deno run -A --unstable https://bit.ly/2YFxCvb
      - run: $HOME/.deno/bin/deno run -A --unstable https://bit.ly/3jTISvV

workflows:
  start-jobs:
    jobs:
      - build-medium
